version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: rvanappeldorn@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
  backend:
    container_name: backend
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
